//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucrarea_4.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        double FahrenheitToCelsius(double temperatureFahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double temperatureFahrenheit);
        
        // CODEGEN: Generating message contract since element name GetListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        Lucrarea_4.ServiceReference1.GetListResponse GetList(Lucrarea_4.ServiceReference1.GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<Lucrarea_4.ServiceReference1.GetListResponse> GetListAsync(Lucrarea_4.ServiceReference1.GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        double CelsiusToFahrenheit(double temperatureCelsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double temperatureCelsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentDateTime", ReplyAction="*")]
        System.DateTime GetCurrentDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetCurrentDateTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertCurrencyToEuro", ReplyAction="*")]
        double ConvertCurrencyToEuro(double amountInRON);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertCurrencyToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConvertCurrencyToEuroAsync(double amountInRON);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public Lucrarea_4.ServiceReference1.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(Lucrarea_4.ServiceReference1.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListRequestBody {
        
        public GetListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lucrarea_4.ServiceReference1.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(Lucrarea_4.ServiceReference1.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lucrarea_4.ServiceReference1.ArrayOfString GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(Lucrarea_4.ServiceReference1.ArrayOfString GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Lucrarea_4.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Lucrarea_4.ServiceReference1.WebService1Soap>, Lucrarea_4.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FahrenheitToCelsius(double temperatureFahrenheit) {
            return base.Channel.FahrenheitToCelsius(temperatureFahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double temperatureFahrenheit) {
            return base.Channel.FahrenheitToCelsiusAsync(temperatureFahrenheit);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lucrarea_4.ServiceReference1.GetListResponse Lucrarea_4.ServiceReference1.WebService1Soap.GetList(Lucrarea_4.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public Lucrarea_4.ServiceReference1.ArrayOfString GetList() {
            Lucrarea_4.ServiceReference1.GetListRequest inValue = new Lucrarea_4.ServiceReference1.GetListRequest();
            inValue.Body = new Lucrarea_4.ServiceReference1.GetListRequestBody();
            Lucrarea_4.ServiceReference1.GetListResponse retVal = ((Lucrarea_4.ServiceReference1.WebService1Soap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lucrarea_4.ServiceReference1.GetListResponse> Lucrarea_4.ServiceReference1.WebService1Soap.GetListAsync(Lucrarea_4.ServiceReference1.GetListRequest request) {
            return base.Channel.GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lucrarea_4.ServiceReference1.GetListResponse> GetListAsync() {
            Lucrarea_4.ServiceReference1.GetListRequest inValue = new Lucrarea_4.ServiceReference1.GetListRequest();
            inValue.Body = new Lucrarea_4.ServiceReference1.GetListRequestBody();
            return ((Lucrarea_4.ServiceReference1.WebService1Soap)(this)).GetListAsync(inValue);
        }
        
        public double CelsiusToFahrenheit(double temperatureCelsius) {
            return base.Channel.CelsiusToFahrenheit(temperatureCelsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double temperatureCelsius) {
            return base.Channel.CelsiusToFahrenheitAsync(temperatureCelsius);
        }
        
        public System.DateTime GetCurrentDateTime() {
            return base.Channel.GetCurrentDateTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetCurrentDateTimeAsync() {
            return base.Channel.GetCurrentDateTimeAsync();
        }
        
        public double ConvertCurrencyToEuro(double amountInRON) {
            return base.Channel.ConvertCurrencyToEuro(amountInRON);
        }
        
        public System.Threading.Tasks.Task<double> ConvertCurrencyToEuroAsync(double amountInRON) {
            return base.Channel.ConvertCurrencyToEuroAsync(amountInRON);
        }
    }
}
